# Generated by Django 5.2.4 on 2026-02-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('cor', models.CharField(default='#167042', max_length=7)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('INCIDENTE_ZABBIX', 'Incidente Zabbix'), ('DATACENTER', 'Datacenter'), ('AMBIENTE', 'Problema de Ambiente'), ('INFO', 'Informação Importante')], max_length=20)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_livro', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='registros', to='livro_monitoramento.tag')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['criado_em'], name='livro_monit_criado__78dad5_idx'), models.Index(fields=['tipo'], name='livro_monit_tipo_f240e0_idx')],
            },
        ),
    ]
