# Generated by Django 5.2.4 on 2026-02-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro_monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Registro',
                'verbose_name_plural': 'Tipos de Registro',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='registro',
            name='etiquetas',
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.RemoveIndex(
            model_name='registro',
            name='livro_monit_criado__78dad5_idx',
        ),
        migrations.RemoveIndex(
            model_name='registro',
            name='livro_monit_tipo_f240e0_idx',
        ),
        migrations.AlterField(
            model_name='registro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='livro_monitoramento.tiporegistro'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
