# Generated by Django 5.2.4 on 2026-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro_monitoramento', '0003_logacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('icone', models.CharField(blank=True, default='🔗', help_text='Ex: 🔗 📄 🟢 📌', max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link/Informação Importante',
                'verbose_name_plural': 'Links/Informações Importantes',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
