# Generated by Django 5.2.4 on 2026-02-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro_monitoramento', '0004_linkimportante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('URL', 'URLs'), ('INFO', 'Informações')], default='URL', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Apoio',
                'verbose_name_plural': 'Categorias de Apoio',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='linkimportante',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Item de Apoio', 'verbose_name_plural': 'Itens de Apoio'},
        ),
        migrations.AlterField(
            model_name='linkimportante',
            name='icone',
            field=models.CharField(blank=True, default='📌', max_length=8),
        ),
        migrations.AddField(
            model_name='linkimportante',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='livro_monitoramento.categoriaapoio'),
        ),
    ]
