# Generated by Django 5.2.4 on 2026-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro_monitoramento', '0005_categoriaapoio_alter_linkimportante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaapoio',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria de Apoio', 'verbose_name_plural': 'Categorias de Apoio'},
        ),
        migrations.RemoveField(
            model_name='categoriaapoio',
            name='tipo',
        ),
    ]
